version: 2
jobs:
  foo:
    docker:
      - image: santhosh123.jfrog.io/docker/ubunut:bionic
    parallelism: 4
    steps:
      - checkout
      - run: echo Hello, world. Yay

workflows:
  version: 2
  circle-test:
    jobs:
      - foo